name: Update App replicas

on:
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        description: "App Name"
        type: string
      replicas:
        required: true
        description: "New replica count"
        type: string

jobs:
  update-replicas:
    runs-on: ubuntu-latest
    steps:
      - run: |
          app_name="${{ inputs.app_name }}"
          echo "trimmed_app_name=$(echo ${app_name} | cut -d '-'' -f 1)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Set replica count
        uses: mikefarah/yq@master
        with:
          cmd: yq -i ".spec.replicas = ${{ inputs.replicas }}" "${{ env.trimmed_app_name }}/${{ env.trimmed_app_name }}-deployment.yaml"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          push: true
          default_author: github_actions
          message: Updated replica count for ${{ inputs.app_name }} to ${{ inputs.replicas }}

